import type { Domain, Flashcard, Question } from "./types";

export const domains: Domain[] = [
  { id: "mobile", exam: "220-1201", name: "Mobile Devices", weight: 13, color: "#36d6b5", description: "Laptop hardware, mobile accessories, connectivity, and device configuration.", topics: ["Laptop components", "Displays and digitizers", "Mobile connectivity", "Accessories"] },
  { id: "networking", exam: "220-1201", name: "Networking", weight: 23, color: "#55a8ff", description: "Protocols, ports, wireless standards, network services, and small-office configuration.", topics: ["TCP/UDP ports", "Wi-Fi standards", "SOHO networks", "Network tools"] },
  { id: "hardware", exam: "220-1201", name: "Hardware", weight: 25, color: "#a78bfa", description: "PC components, storage, memory, printers, cables, and power systems.", topics: ["Motherboards and CPUs", "RAM and storage", "Power and cooling", "Printers"] },
  { id: "virtualization", exam: "220-1201", name: "Virtualization & Cloud", weight: 11, color: "#f2b84b", description: "Virtual machines, cloud delivery models, and resource concepts.", topics: ["Hypervisors", "Cloud models", "Virtual resources", "Containers"] },
  { id: "hw-troubleshooting", exam: "220-1201", name: "Hardware Troubleshooting", weight: 28, color: "#ff7c70", description: "Systematic diagnosis of hardware, network, mobile, and printer failures.", topics: ["Troubleshooting method", "PC symptoms", "Network faults", "Printer issues"] },
  { id: "os", exam: "220-1202", name: "Operating Systems", weight: 28, color: "#55a8ff", description: "Windows, Linux, macOS, command-line tools, installation, and administration.", topics: ["Windows editions", "System utilities", "Linux/macOS", "OS deployment"] },
  { id: "security", exam: "220-1202", name: "Security", weight: 28, color: "#36d6b5", description: "Threats, hardening, authentication, malware response, and data protection.", topics: ["Threats and attacks", "Access control", "Device hardening", "Malware removal"] },
  { id: "sw-troubleshooting", exam: "220-1202", name: "Software Troubleshooting", weight: 23, color: "#ff7c70", description: "Diagnose operating system, application, security, and mobile software issues.", topics: ["Windows symptoms", "Application failures", "Mobile issues", "Security symptoms"] },
  { id: "operations", exam: "220-1202", name: "Operational Procedures", weight: 21, color: "#f2b84b", description: "Safety, professionalism, documentation, change management, and backup practices.", topics: ["Documentation", "Safety and environment", "Professionalism", "Backup and recovery"] }
];

export const questions: Question[] = [
  { id: "q01", exam: "220-1201", domain: "mobile", difficulty: "Foundation", prompt: "A laptop screen is very dim, but a faint image is visible under a flashlight. Which component is the most likely cause?", options: ["Wi-Fi antenna", "Backlight circuit", "Digitizer", "Webcam module"], answer: 1, explanation: "A visible image means the LCD is producing pixels. The failed illumination points to the LED backlight or its power circuitry.", objective: "Diagnose laptop display components" },
  { id: "q02", exam: "220-1201", domain: "mobile", difficulty: "Intermediate", prompt: "Which technology most commonly enables tap-to-pay at a retail terminal?", options: ["NFC", "GPS", "IR", "LTE"], answer: 0, explanation: "Near-field communication provides the very short-range wireless link used by contactless payment systems.", objective: "Configure mobile accessories and connectivity" },
  { id: "q03", exam: "220-1201", domain: "networking", difficulty: "Foundation", prompt: "Which port should be allowed for secure web traffic to an internal server?", options: ["22", "53", "80", "443"], answer: 3, explanation: "HTTPS uses TCP port 443. Port 80 is unencrypted HTTP, 22 is SSH, and 53 is DNS.", objective: "Compare common ports and protocols" },
  { id: "q04", exam: "220-1201", domain: "networking", difficulty: "Intermediate", prompt: "A workstation receives an address beginning with 169.254. Which service most likely failed?", options: ["DNS", "DHCP", "NTP", "SNMP"], answer: 1, explanation: "An APIPA address in 169.254.0.0/16 is self-assigned when a Windows client cannot reach DHCP.", objective: "Troubleshoot common network services" },
  { id: "q05", exam: "220-1201", domain: "networking", difficulty: "Advanced", prompt: "A busy office needs the highest practical Wi-Fi capacity and has modern clients. Which band should be preferred when range through walls is not the priority?", options: ["2.4 GHz", "5 GHz or 6 GHz", "900 MHz", "Bluetooth"], answer: 1, explanation: "The 5 and 6 GHz bands offer more channels and typically less congestion, at the cost of shorter range and weaker wall penetration.", objective: "Compare wireless networking technologies" },
  { id: "q06", exam: "220-1201", domain: "hardware", difficulty: "Foundation", prompt: "Which storage interface connects directly through PCI Express lanes and commonly uses the M.2 form factor?", options: ["SATA", "NVMe", "SAS", "PATA"], answer: 1, explanation: "NVMe is designed for nonvolatile storage over PCIe and is common in M.2 SSDs.", objective: "Compare storage devices and interfaces" },
  { id: "q07", exam: "220-1201", domain: "hardware", difficulty: "Intermediate", prompt: "A PC shuts down during gaming and immediately feels very hot near the CPU. What should be checked first?", options: ["Display resolution", "CPU cooling assembly", "Keyboard layout", "File permissions"], answer: 1, explanation: "A thermal shutdown under load points first to airflow, fan operation, heatsink seating, and thermal compound.", objective: "Install and configure cooling" },
  { id: "q08", exam: "220-1201", domain: "hardware", difficulty: "Intermediate", prompt: "Which printer component permanently bonds toner to paper using heat and pressure?", options: ["Pickup roller", "Transfer belt", "Fuser", "Duplexer"], answer: 2, explanation: "The fuser assembly melts and presses toner onto the page.", objective: "Maintain laser printers" },
  { id: "q09", exam: "220-1201", domain: "virtualization", difficulty: "Foundation", prompt: "Which cloud model delivers a complete application through a browser while the provider manages the platform and infrastructure?", options: ["IaaS", "SaaS", "PaaS", "DaaS"], answer: 1, explanation: "Software as a Service delivers the finished application; users generally manage only their data and settings.", objective: "Summarize cloud service models" },
  { id: "q10", exam: "220-1201", domain: "virtualization", difficulty: "Intermediate", prompt: "What feature lets several virtual machines share one physical host while remaining logically isolated?", options: ["Hypervisor", "Load balancer", "Print server", "Proxy cache"], answer: 0, explanation: "A hypervisor allocates host resources to isolated virtual machines and mediates hardware access.", objective: "Explain virtualization concepts" },
  { id: "q11", exam: "220-1201", domain: "hw-troubleshooting", difficulty: "Intermediate", prompt: "After identifying the probable cause of a failed PC, what is the next step in the standard troubleshooting methodology?", options: ["Document findings", "Establish a theory", "Test the theory", "Replace every suspect part"], answer: 2, explanation: "After establishing a theory of probable cause, test that theory to confirm the cause before planning the fix.", objective: "Apply troubleshooting methodology" },
  { id: "q12", exam: "220-1201", domain: "hw-troubleshooting", difficulty: "Advanced", prompt: "A laser printer produces a repeated mark at equal intervals down every page. What is the most likely source?", options: ["A damaged rotating component", "Low network bandwidth", "Incorrect paper orientation", "A disabled spooler"], answer: 0, explanation: "A defect on a drum, roller, or fuser repeats each time that component completes a rotation, creating evenly spaced marks.", objective: "Troubleshoot printer output" },
  { id: "q13", exam: "220-1202", domain: "os", difficulty: "Foundation", prompt: "Which Windows command displays the IP configuration for all network adapters?", options: ["ipconfig /all", "sfc /scannow", "diskpart", "gpupdate"], answer: 0, explanation: "ipconfig /all displays detailed TCP/IP configuration including addresses, gateways, DNS, DHCP, and MAC addresses.", objective: "Use Windows command-line tools" },
  { id: "q14", exam: "220-1202", domain: "os", difficulty: "Intermediate", prompt: "Which Windows file system supports permissions, encryption, compression, and large files?", options: ["FAT32", "exFAT", "NTFS", "ext4"], answer: 2, explanation: "NTFS is the standard Windows system volume format and supports ACL permissions, EFS, compression, journaling, and large files.", objective: "Compare file systems" },
  { id: "q15", exam: "220-1202", domain: "os", difficulty: "Intermediate", prompt: "Which Linux command changes file permissions?", options: ["grep", "chmod", "pwd", "ps"], answer: 1, explanation: "chmod changes permission bits; chown changes ownership.", objective: "Use basic Linux commands" },
  { id: "q16", exam: "220-1202", domain: "security", difficulty: "Foundation", prompt: "What principle gives a user only the permissions necessary to perform assigned duties?", options: ["Open access", "Least privilege", "Single sign-on", "Implicit trust"], answer: 1, explanation: "Least privilege limits access and reduces the damage possible from mistakes or compromised accounts.", objective: "Apply access-control best practices" },
  { id: "q17", exam: "220-1202", domain: "security", difficulty: "Intermediate", prompt: "An attacker calls an employee while pretending to be the help desk and asks for a password. What attack is this?", options: ["Tailgating", "Vishing", "Shoulder surfing", "Evil twin"], answer: 1, explanation: "Voice phishing, or vishing, uses phone calls or voice systems to manipulate a target into revealing information.", objective: "Compare social engineering attacks" },
  { id: "q18", exam: "220-1202", domain: "security", difficulty: "Advanced", prompt: "A suspected malware infection is active on a workstation. What should the technician do first in the malware-removal process?", options: ["Enable System Restore", "Quarantine the system", "Educate the user", "Schedule scans"], answer: 1, explanation: "Isolate or quarantine the affected system first to prevent further spread or communication while remediation begins.", objective: "Apply malware-removal procedures" },
  { id: "q19", exam: "220-1202", domain: "sw-troubleshooting", difficulty: "Intermediate", prompt: "Windows starts normally but an application crashes immediately after an update. What is the best first action?", options: ["Replace the motherboard", "Check application and event logs", "Reformat every drive", "Disable the display"], answer: 1, explanation: "Logs can identify the faulting module, dependency, or error code and support a targeted rollback or repair.", objective: "Troubleshoot application failures" },
  { id: "q20", exam: "220-1202", domain: "sw-troubleshooting", difficulty: "Advanced", prompt: "A browser repeatedly redirects to unfamiliar search pages and displays unwanted toolbars. Which cause is most likely?", options: ["Boot-sector failure", "Browser hijacker", "Bad RAM timing", "Defective PSU"], answer: 1, explanation: "Redirects, changed search settings, and unwanted extensions are classic browser-hijacker or potentially unwanted application symptoms.", objective: "Identify malware symptoms" },
  { id: "q21", exam: "220-1202", domain: "operations", difficulty: "Foundation", prompt: "Before making a significant production configuration change, which item should be documented?", options: ["Only the technician name", "Scope, risk, rollback plan, and approval", "The user's wallpaper", "Unrelated inventory"], answer: 1, explanation: "Sound change management records purpose, scope, impact, risk, approval, schedule, testing, and a rollback plan.", objective: "Explain change-management procedures" },
  { id: "q22", exam: "220-1202", domain: "operations", difficulty: "Intermediate", prompt: "Which fire extinguisher class is appropriate for energized electrical equipment in the United States?", options: ["Class A", "Class B", "Class C", "Class K"], answer: 2, explanation: "Class C applies to energized electrical equipment. Always follow site safety policy and local labeling.", objective: "Apply workplace safety procedures" },
  { id: "q23", exam: "220-1202", domain: "operations", difficulty: "Intermediate", prompt: "Which backup contains all selected data changed since the last full backup?", options: ["Incremental", "Differential", "Synthetic", "Snapshot only"], answer: 1, explanation: "A differential backup accumulates all changes since the last full backup. An incremental records changes since the last backup of any type.", objective: "Compare backup methods" },
  { id: "q24", exam: "220-1202", domain: "operations", difficulty: "Advanced", prompt: "A frustrated user reports a recurring issue. Which response best demonstrates professional communication?", options: ["Interrupt with a quick guess", "Use technical jargon to establish authority", "Listen, clarify impact, set expectations, and document", "Blame the prior technician"], answer: 2, explanation: "Active listening, clear questions, respectful language, realistic expectations, and accurate documentation support both the user and the technical process.", objective: "Use professional communication techniques" }
];

export const flashcards: Flashcard[] = [
  { id: "f01", domain: "networking", front: "HTTPS / SSH / RDP ports", back: "HTTPS: 443 TCP; SSH: 22 TCP; RDP: 3389 TCP/UDP." },
  { id: "f02", domain: "networking", front: "DHCP DORA", back: "Discover, Offer, Request, Acknowledge: the basic IPv4 lease sequence." },
  { id: "f03", domain: "hardware", front: "NVMe vs SATA", back: "NVMe uses PCIe and parallel queues; SATA SSDs use the AHCI/SATA path and are generally slower." },
  { id: "f04", domain: "hardware", front: "Laser printing process", back: "Processing, charging, exposing, developing, transferring, fusing, cleaning." },
  { id: "f05", domain: "mobile", front: "NFC", back: "Very short-range wireless communication used for tap-to-pay, badges, and quick pairing." },
  { id: "f06", domain: "virtualization", front: "Type 1 vs Type 2 hypervisor", back: "Type 1 runs on hardware; Type 2 runs as an application on a host operating system." },
  { id: "f07", domain: "os", front: "Windows repair commands", back: "SFC checks protected system files. DISM services and repairs the Windows image." },
  { id: "f08", domain: "os", front: "chmod 755", back: "Owner: read/write/execute. Group and others: read/execute." },
  { id: "f09", domain: "security", front: "AAA", back: "Authentication verifies identity, authorization grants permissions, accounting records activity." },
  { id: "f10", domain: "security", front: "Malware response opening steps", back: "Identify symptoms, quarantine the system, disable System Restore when appropriate, remediate, update, scan, re-enable, educate." },
  { id: "f11", domain: "operations", front: "Differential vs incremental backup", back: "Differential: changes since full. Incremental: changes since the latest backup of any type." },
  { id: "f12", domain: "hw-troubleshooting", front: "Troubleshooting sequence", back: "Identify, theorize, test, plan and implement, verify and prevent, document." }
];
